package ee.ut.cs.unispect.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;





/**
 * This class was autogenerated by Torque on:
 *
 * [Fri Jan 17 19:55:56 EET 2025]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to UnispectCompound
 */
public abstract class BaseUnispectCompound extends BaseObject
{
    /** Serial version */
    private static final long serialVersionUID = 1737136556691L;

    /** The Peer class */
    private static final UnispectCompoundPeer peer =
        new UnispectCompoundPeer();


    /** The value for the compoundId field */
    private int compoundId;

    /** The value for the date field */
    private Date date;

    /** The value for the inchiKey field */
    private String inchiKey;

    /** The value for the inchi field */
    private String inchi;


    /**
     * Get the CompoundId
     *
     * @return int
     */
    public int getCompoundId()
    {
        return compoundId;
    }


    /**
     * Set the value of CompoundId
     *
     * @param v new value
     */
    public void setCompoundId(int v) throws TorqueException
    {

        if (this.compoundId != v)
        {
            this.compoundId = v;
            setModified(true);
        }



        // update associated UnispectSpectrum
        if (collUnispectSpectrums != null)
        {
            for (int i = 0; i < collUnispectSpectrums.size(); i++)
            {
                ((UnispectSpectrum) collUnispectSpectrums.get(i))
                        .setCompoundId(v);
            }
        }
    }

    /**
     * Get the Date
     *
     * @return Date
     */
    public Date getDate()
    {
        return date;
    }


    /**
     * Set the value of Date
     *
     * @param v new value
     */
    public void setDate(Date v) 
    {

        if (!ObjectUtils.equals(this.date, v))
        {
            this.date = v;
            setModified(true);
        }


    }

    /**
     * Get the InchiKey
     *
     * @return String
     */
    public String getInchiKey()
    {
        return inchiKey;
    }


    /**
     * Set the value of InchiKey
     *
     * @param v new value
     */
    public void setInchiKey(String v) 
    {

        if (!ObjectUtils.equals(this.inchiKey, v))
        {
            this.inchiKey = v;
            setModified(true);
        }


    }

    /**
     * Get the Inchi
     *
     * @return String
     */
    public String getInchi()
    {
        return inchi;
    }


    /**
     * Set the value of Inchi
     *
     * @param v new value
     */
    public void setInchi(String v) 
    {

        if (!ObjectUtils.equals(this.inchi, v))
        {
            this.inchi = v;
            setModified(true);
        }


    }

       


    /**
     * Collection to store aggregation of collUnispectSpectrums
     */
    protected List<UnispectSpectrum> collUnispectSpectrums;

    /**
     * Temporary storage of collUnispectSpectrums to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initUnispectSpectrums()
    {
        if (collUnispectSpectrums == null)
        {
            collUnispectSpectrums = new ArrayList<UnispectSpectrum>();
        }
    }


    /**
     * Method called to associate a UnispectSpectrum object to this object
     * through the UnispectSpectrum foreign key attribute
     *
     * @param l UnispectSpectrum
     * @throws TorqueException
     */
    public void addUnispectSpectrum(UnispectSpectrum l) throws TorqueException
    {
        getUnispectSpectrums().add(l);
        l.setUnispectCompound((UnispectCompound) this);
    }

    /**
     * Method called to associate a UnispectSpectrum object to this object
     * through the UnispectSpectrum foreign key attribute using connection.
     *
     * @param l UnispectSpectrum
     * @throws TorqueException
     */
    public void addUnispectSpectrum(UnispectSpectrum l, Connection con) throws TorqueException
    {
        getUnispectSpectrums(con).add(l);
        l.setUnispectCompound((UnispectCompound) this);
    }

    /**
     * The criteria used to select the current contents of collUnispectSpectrums
     */
    private Criteria lastUnispectSpectrumsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUnispectSpectrums(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<UnispectSpectrum> getUnispectSpectrums()
        throws TorqueException
    {
        if (collUnispectSpectrums == null)
        {
            collUnispectSpectrums = getUnispectSpectrums(new Criteria(10));
        }
        return collUnispectSpectrums;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnispectCompound has previously
     * been saved, it will retrieve related UnispectSpectrums from storage.
     * If this UnispectCompound is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List<UnispectSpectrum> getUnispectSpectrums(Criteria criteria) throws TorqueException
    {
        if (collUnispectSpectrums == null)
        {
            if (isNew())
            {
               collUnispectSpectrums = new ArrayList<UnispectSpectrum>();
            }
            else
            {
                criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId() );
                collUnispectSpectrums = UnispectSpectrumPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
                if (!lastUnispectSpectrumsCriteria.equals(criteria))
                {
                    collUnispectSpectrums = UnispectSpectrumPeer.doSelect(criteria);
                }
            }
        }
        lastUnispectSpectrumsCriteria = criteria;

        return collUnispectSpectrums;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUnispectSpectrums(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<UnispectSpectrum> getUnispectSpectrums(Connection con) throws TorqueException
    {
        if (collUnispectSpectrums == null)
        {
            collUnispectSpectrums = getUnispectSpectrums(new Criteria(10), con);
        }
        return collUnispectSpectrums;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnispectCompound has previously
     * been saved, it will retrieve related UnispectSpectrums from storage.
     * If this UnispectCompound is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List<UnispectSpectrum> getUnispectSpectrums(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collUnispectSpectrums == null)
        {
            if (isNew())
            {
               collUnispectSpectrums = new ArrayList<UnispectSpectrum>();
            }
            else
            {
                 criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
                 collUnispectSpectrums = UnispectSpectrumPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                 criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
                 if (!lastUnispectSpectrumsCriteria.equals(criteria))
                 {
                     collUnispectSpectrums = UnispectSpectrumPeer.doSelect(criteria, con);
                 }
             }
         }
         lastUnispectSpectrumsCriteria = criteria;

         return collUnispectSpectrums;
     }











    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnispectCompound is new, it will return
     * an empty collection; or if this UnispectCompound has previously
     * been saved, it will retrieve related UnispectSpectrums from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in UnispectCompound.
     */
    protected List<UnispectSpectrum> getUnispectSpectrumsJoinUnispectSpectrumType(Criteria criteria)
        throws TorqueException
    {
        if (collUnispectSpectrums == null)
        {
            if (isNew())
            {
               collUnispectSpectrums = new ArrayList<UnispectSpectrum>();
            }
            else
            {
                criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
                collUnispectSpectrums = UnispectSpectrumPeer.doSelectJoinUnispectSpectrumType(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
            if (!lastUnispectSpectrumsCriteria.equals(criteria))
            {
                collUnispectSpectrums = UnispectSpectrumPeer.doSelectJoinUnispectSpectrumType(criteria);
            }
        }
        lastUnispectSpectrumsCriteria = criteria;

        return collUnispectSpectrums;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnispectCompound is new, it will return
     * an empty collection; or if this UnispectCompound has previously
     * been saved, it will retrieve related UnispectSpectrums from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in UnispectCompound.
     */
    protected List<UnispectSpectrum> getUnispectSpectrumsJoinUnispectCompound(Criteria criteria)
        throws TorqueException
    {
        if (collUnispectSpectrums == null)
        {
            if (isNew())
            {
               collUnispectSpectrums = new ArrayList<UnispectSpectrum>();
            }
            else
            {
                criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
                collUnispectSpectrums = UnispectSpectrumPeer.doSelectJoinUnispectCompound(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
            if (!lastUnispectSpectrumsCriteria.equals(criteria))
            {
                collUnispectSpectrums = UnispectSpectrumPeer.doSelectJoinUnispectCompound(criteria);
            }
        }
        lastUnispectSpectrumsCriteria = criteria;

        return collUnispectSpectrums;
    }









    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this UnispectCompound is new, it will return
     * an empty collection; or if this UnispectCompound has previously
     * been saved, it will retrieve related UnispectSpectrums from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in UnispectCompound.
     */
    protected List<UnispectSpectrum> getUnispectSpectrumsJoinUnispectSource(Criteria criteria)
        throws TorqueException
    {
        if (collUnispectSpectrums == null)
        {
            if (isNew())
            {
               collUnispectSpectrums = new ArrayList<UnispectSpectrum>();
            }
            else
            {
                criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
                collUnispectSpectrums = UnispectSpectrumPeer.doSelectJoinUnispectSource(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.add(UnispectSpectrumPeer.COMPOUND_ID, getCompoundId());
            if (!lastUnispectSpectrumsCriteria.equals(criteria))
            {
                collUnispectSpectrums = UnispectSpectrumPeer.doSelectJoinUnispectSource(criteria);
            }
        }
        lastUnispectSpectrumsCriteria = criteria;

        return collUnispectSpectrums;
    }



        
    private static List<String> fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List<String> getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList<String>();
            fieldNames.add("CompoundId");
            fieldNames.add("Date");
            fieldNames.add("InchiKey");
            fieldNames.add("Inchi");
            fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("CompoundId"))
        {
            return new Integer(getCompoundId());
        }
        if (name.equals("Date"))
        {
            return getDate();
        }
        if (name.equals("InchiKey"))
        {
            return getInchiKey();
        }
        if (name.equals("Inchi"))
        {
            return getInchi();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value )
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("CompoundId"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setCompoundId(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Date"))
        {
            // Object fields can be null
            if (value != null && ! Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setDate((Date) value);
            return true;
        }
        if (name.equals("InchiKey"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setInchiKey((String) value);
            return true;
        }
        if (name.equals("Inchi"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setInchi((String) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (name.equals(UnispectCompoundPeer.COMPOUND_ID))
        {
            return new Integer(getCompoundId());
        }
        if (name.equals(UnispectCompoundPeer.DATE))
        {
            return getDate();
        }
        if (name.equals(UnispectCompoundPeer.INCHI_KEY))
        {
            return getInchiKey();
        }
        if (name.equals(UnispectCompoundPeer.INCHI))
        {
            return getInchi();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
      if (UnispectCompoundPeer.COMPOUND_ID.equals(name))
        {
            return setByName("CompoundId", value);
        }
      if (UnispectCompoundPeer.DATE.equals(name))
        {
            return setByName("Date", value);
        }
      if (UnispectCompoundPeer.INCHI_KEY.equals(name))
        {
            return setByName("InchiKey", value);
        }
      if (UnispectCompoundPeer.INCHI.equals(name))
        {
            return setByName("Inchi", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return new Integer(getCompoundId());
        }
        if (pos == 1)
        {
            return getDate();
        }
        if (pos == 2)
        {
            return getInchiKey();
        }
        if (pos == 3)
        {
            return getInchi();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
    if (position == 0)
        {
            return setByName("CompoundId", value);
        }
    if (position == 1)
        {
            return setByName("Date", value);
        }
    if (position == 2)
        {
            return setByName("InchiKey", value);
        }
    if (position == 3)
        {
            return setByName("Inchi", value);
        }
        return false;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
        save(UnispectCompoundPeer.DATABASE_NAME);
    }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
        try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
    }

    /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
        {
            alreadyInSave = true;



            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    UnispectCompoundPeer.doInsert((UnispectCompound) this, con);
                    setNew(false);
                }
                else
                {
                    UnispectCompoundPeer.doUpdate((UnispectCompound) this, con);
                }
            }


            if (collUnispectSpectrums != null)
            {
                for (int i = 0; i < collUnispectSpectrums.size(); i++)
                {
                    ((UnispectSpectrum) collUnispectSpectrums.get(i)).save(con);
                }
            }
            alreadyInSave = false;
        }
    }


    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key compoundId ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
        setCompoundId(((NumberKey) key).intValue());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
        setCompoundId(Integer.parseInt(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getCompoundId());
    }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public UnispectCompound copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     */
    public UnispectCompound copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     */
    public UnispectCompound copy(boolean deepcopy) throws TorqueException
    {
        return copyInto(new UnispectCompound(), deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     */
    public UnispectCompound copy(boolean deepcopy, Connection con) throws TorqueException
    {
        return copyInto(new UnispectCompound(), deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     */
    protected UnispectCompound copyInto(UnispectCompound copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

  
    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     */
    protected UnispectCompound copyInto(UnispectCompound copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     */
    protected UnispectCompound copyInto(UnispectCompound copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setCompoundId(compoundId);
        copyObj.setDate(date);
        copyObj.setInchiKey(inchiKey);
        copyObj.setInchi(inchi);

        copyObj.setCompoundId( 0);

        if (deepcopy)
        {


        List<UnispectSpectrum> vUnispectSpectrums = getUnispectSpectrums();
        if (vUnispectSpectrums != null)
        {
            for (int i = 0; i < vUnispectSpectrums.size(); i++)
            {
                UnispectSpectrum obj =  vUnispectSpectrums.get(i);
                copyObj.addUnispectSpectrum(obj.copy());
            }
        }
        else
        {
            copyObj.collUnispectSpectrums = null;
        }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     */
    protected UnispectCompound copyInto(UnispectCompound copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setCompoundId(compoundId);
        copyObj.setDate(date);
        copyObj.setInchiKey(inchiKey);
        copyObj.setInchi(inchi);

        copyObj.setCompoundId( 0);

        if (deepcopy)
        {


        List<UnispectSpectrum> vUnispectSpectrums = getUnispectSpectrums(con);
        if (vUnispectSpectrums != null)
        {
            for (int i = 0; i < vUnispectSpectrums.size(); i++)
            {
                UnispectSpectrum obj =  vUnispectSpectrums.get(i);
                copyObj.addUnispectSpectrum(obj.copy(con), con);
            }
        }
        else
        {
            copyObj.collUnispectSpectrums = null;
        }
        }
        return copyObj;
    }
    
    

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public UnispectCompoundPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     */
    public TableMap getTableMap() throws TorqueException
    {
        return UnispectCompoundPeer.getTableMap();
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("UnispectCompound:\n");
        str.append("CompoundId = ")
           .append(getCompoundId())
           .append("\n");
        str.append("Date = ")
           .append(getDate())
           .append("\n");
        str.append("InchiKey = ")
           .append(getInchiKey())
           .append("\n");
        str.append("Inchi = ")
           .append(getInchi())
           .append("\n");
        return(str.toString());
    }
}
