package ee.ut.cs.unispect.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Jan 17 18:48:49 EET 2025]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UnispectCompoundPeer
    extends ee.ut.cs.unispect.om.BaseUnispectCompoundPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1737132529364L;

}
